# -*- coding: utf-8 -*-
{
    'name': 'Salon Management',
    'summary': """Salon Management with Online Booking System""",
    'version': '1.0.0.1',
    'author': 'Hassan Shehata',
    'company': 'PiTechnologies',
    "category": "Industries",
    'depends': ['base', 'account', 'mail', 'website'],
    'data': ['views/salon_holiday.xml',
             'views/salon_data.xml',
             'views/salon_management_chair.xml',
             'views/salon_management_services.xml',
             'views/salon_order_view.xml',
             'views/salon_management_dashboard.xml',
             'views/booking_backend.xml',
             'views/salon_bookings.xml',
             'views/salon_email_template.xml',
             'views/salon_config.xml',
             'views/working_hours.xml',
             'security/ir.model.access.csv',
             ],
    'demo': [
        'views/booking_demo.xml',
    ],
    'images': ['static/description/banner.jpg'],
    'license': 'LGPL-3',
    'installable': True,
    'application': True,
}
